# Site settings
title: GoodHaHa
email: sunwuhao@buaa.edu.cn
description: 孙吴昊的博客

github_username: GoodHaHa
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# 分页
paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false

encoding: UTF-8